name: Frontend

on:
  push:
    branches: [ main ]
    paths:
      - frontend/**
  pull_request:
    branches: [ main ]

jobs:

  verified:
    runs-on: ubuntu-latest
    needs:
      - test
      - typecheck
      - build
    steps:
      - run: echo "And there's colors like green"

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: prep pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate
      - name: pnpm i
        run: pnpm i
        working-directory: frontend
      - name: vitest
        run: pnpm test
        working-directory: frontend

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: prep pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate
      - name: pnpm i
        run: pnpm i
        working-directory: frontend
      - name: svelte-check
        run: pnpm check
        working-directory: frontend

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: prep pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate
      - name: pnpm i
        run: pnpm i
        working-directory: frontend
      - name: vite
        run: pnpm build
        working-directory: frontend
