name: GH Release
run-name: Create ${{ inputs.tag }} GitHub release

on:
  workflow_call:
    inputs:
      prerelease:
        type: string
        required: true
      tag:
        type: string
        required: true
      version:
        type: string
        required: true

jobs:
  create-gh-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true
      - name: Create release
        run: ./.github/workflows/create_gh_release.sh ./artifacts
        env:
          GH_TOKEN: ${{ github.token }}
          CHANGELOG: ${{ inputs.prerelease == 'true' && 'Unreleased' || inputs.version }}
          VERSION: ${{ inputs.version }}
          TAG: ${{ inputs.tag }}
          PRERELEASE: ${{ inputs.prerelease }}
