name: Create GitHub release
run-name: Create ${{ inputs.tag }} GitHub release

on:
  workflow_call:
    inputs:
      title:
        type: string
        required: true
      release_notes:
        type: string
        required: true
      prerelease:
        type: string
        required: true
      latest:
        type: string
        required: true
      tag:
        type: string
        required: true
      artifacts_path:
        type: string

jobs:
  create-gh-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - if: inputs.artifacts_path != ''
        uses: actions/download-artifact@v4
        with:
          path: ${{ inputs.artifacts_path }}
          merge-multiple: true
      - name: create github release
        env:
          GH_TOKEN: ${{ github.token }}
        working-directory: ${{ inputs.artifacts_path }}
        run: |
          echo "${{ inputs.release_notes  }}" | base64 --decode > release_notes.md
          _assets=$(ls .)
          gh release create "${{ inputs.tag }}" \
            --repo="${{ github.repository }}" \
            --latest="${{ inputs.latest }}" \
            --prerelease="${{ inputs.prerelease }}" \
            --notes-file release_notes.md \
            --title "${{ inputs.title }}" \
            $_assets
