name: Publish
run-name: Create ${{ inputs.semver-bump }} release

on:
  workflow_dispatch:
    inputs:
      semver-bump:
        description: Semver bump release type
        required: true
        type: choice
        default: alpha
        options:
          - major
          - minor
          - patch
          - release
          - rc
          - beta
          - alpha

concurrency: publish

jobs:
  check-build-params:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: check changelogs if not prerelease
      run: |
        ./.github/workflows/changelog_check.sh cli/CHANGELOG.md
        ./.github/workflows/changelog_check.sh git/CHANGELOG.md

  verify:
    needs: [check-build-params]
    uses: ./.github/workflows/verify.yml

  publish-cargo-crates:
    runs-on: ubuntu-latest
    needs: verify
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: rustup install stable
      - uses: swatinem/rust-cache@v2
        with:
          cache-bin: false
      - name: install cargo release
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          cargo binstall --no-confirm cargo-release
      - name: cargo release
        run: |
          git config --global user.name "Adam McKee"
          git config --global user.email "adam.be.g84d@gmail.com"
          cargo release --no-confirm -x ${{ inputs.semver-bump }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
      - id: version
        run: |
          VERSION=$(awk -F ' = ' '$1 ~ /version/ { gsub(/[\"]/, "", $2); printf("%s",$2) }' cli/Cargo.toml)
          TAG_NAME="maestro-v$VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "tag=$TAG_NAME" >> "$GITHUB_OUTPUT"
    outputs:
      tag: ${{ steps.version.outputs.tag }}
      version: ${{ steps.version.outputs.version }}

  create-gh-release:
    needs: [verify, publish-cargo-crates]
    secrets: inherit
    permissions:
      contents: write
    uses: ./.github/workflows/gh_release.yml
    with:
      tag: ${{ needs.publish-cargo-crates.outputs.tag }}
      version: ${{ needs.publish-cargo-crates.outputs.version }}
      prerelease: ${{ contains(fromJSON('["rc", "beta", "alpha"]'), inputs.semver-bump) && 'true' || 'false' }}
