name: Create release notes
run-name: Create ${{ inputs.git_tag }} release notes

on:
  workflow_call:
    inputs:
      package_path:
        type: string
        required: true
      crate_version:
        type: string
        required: true
      git_tag:
        type: string
        required: true
      prerelease:
        type: boolean
        required: true
    outputs:
      notes:
        value: ${{ jobs.create.outputs.notes }}

jobs:
  create:
    runs-on: ubuntu-latest
    outputs:
      notes: ${{ steps.notes.outputs.notes }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          ref: ${{ inputs.git_tag }}
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: npm i -g @eighty4/changelog
      - id: notes
        env:
          CHANGELOG_TAG: ${{ inputs.prerelease && 'Unreleased' || format('v{0}', inputs.crate_version) }}
          CRATE_VERSION: ${{ inputs.crate_version }}
          INSTALL_SPECIFIER: ${{ inputs.prerelease && format('@{0}', inputs.crate_version) || '' }}
        run: |
          echo "#### Published to crates.io as [maestro](https://crates.io/crates/maestro/$CRATE_VERSION)" >> release_notes.md
          echo >> release_notes.md
          echo "\`\`\`cargo install maestro$INSTALL_SPECIFIER\`\`\`" >> release_notes.md
          echo >> release_notes.md

          echo "## Release notes" >> release_notes.md
          echo >> release_notes.md
          changelog get "$CHANGELOG_TAG" --changelog-file "${{ inputs.package_path }}/CHANGELOG.md" >> release_notes.md
          echo >> release_notes.md

          RELEASE_NOTES=$(cat release_notes.md | base64 -w 0)
          echo "notes=$RELEASE_NOTES" >> "$GITHUB_OUTPUT"
