name: Release

on:
  push:
    tags:
      - v**

jobs:

  verified:
    uses: ./.github/workflows/verify.yml

  release:
    runs-on: ubuntu-22.04
    needs: verified
    outputs:
      release_id: ${{steps.create.outputs.release_id}}
      upload_hostname: ${{steps.create.outputs.upload_hostname}}
      version: ${{steps.create.outputs.version}}
    steps:
      - name: create release
        id: create
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
        run: |
          VERSION=${GITHUB_REF##*/}
          CREATED_RELEASE=$(gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/eighty4/maestro/releases \
            -f tag_name="$VERSION" \
            -f name="$VERSION" \
            -f body="$VERSION release" \
            -F draft=false \
            -F prerelease=false \
            -F generate_release_notes=false)
          echo "release_id=$(echo $CREATED_RELEASE | jq '.id')" >> "$GITHUB_OUTPUT"
          echo "upload_hostname=$(echo $CREATED_RELEASE | jq '.upload_url' | cut -d'/' -f3)" >> "$GITHUB_OUTPUT"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

  release-artifacts:
    runs-on: ubuntu-22.04
    needs: release
    strategy:
      matrix:
        include:
          - platform: darwin
            architecture: amd64
          - platform: darwin
            architecture: arm64
          - platform: linux
            architecture: 386
          - platform: linux
            architecture: amd64
          - platform: linux
            architecture: arm
          - platform: linux
            architecture: arm64
          - platform: windows
            architecture: 386
          - platform: windows
            architecture: amd64
          - platform: windows
            architecture: arm64
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.19.5
      - name: build
        env:
          RELEASE_ID: ${{needs.release.outputs.release_id}}
          UPLOAD_HOSTNAME: ${{needs.release.outputs.upload_hostname}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
        run: |
          FILENAME=maestro-${{matrix.platform}}-${{matrix.architecture}}
          if [[ "${{matrix.platform}}" == "windows" ]]; then
            FILENAME=$FILENAME.exe
          fi
          GOOS=${{matrix.platform}} GOARCH=${{matrix.architecture}} go build -o dist/$FILENAME
          curl --fail --silent -L -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Content-Type: $(file dist/$FILENAME -b --mime-type)" \
            https://$UPLOAD_HOSTNAME/repos/eighty4/maestro/releases/$RELEASE_ID/assets?name=$FILENAME \
            --data-binary "@dist/$FILENAME"

  cleanup:
    runs-on: ubuntu-22.04
    needs:
      - release
      - release-artifacts
    if: ${{always() && contains(needs.release-artifacts.result, 'failure')}}
    steps:
      - name: delete failed release
        env:
          RELEASE_ID: ${{needs.release.outputs.release_id}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
        run: |
          gh api \
            --method DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/eighty4/maestro/releases/$RELEASE_ID

  update-pkg-go-dev:
    runs-on: ubuntu-22.04
    needs:
      - release
      - release-artifacts
    steps:
      - name: delete failed release
        env:
          VERSION: ${{needs.release.outputs.version}}
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
        run: |
          go mod init update-pkg-go-dev
          GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/eighty4/maestro@$VERSION
          GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/eighty4/maestro/composable
          GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/eighty4/maestro/git
          GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/eighty4/maestro/testutil
          GOPROXY=https://proxy.golang.org GO111MODULE=on go get github.com/eighty4/maestro/util
