name: Maestro CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.5
      - run: git config --global init.defaultBranch main
      - run: git config --global user.name "Adam McKee"
      - run: git config --global user.email "adam.be.g84d@gmail.com"
      - run: go build
      - run: go list -f '{{.Dir}}' -m | xargs go test
      - run: go mod tidy
      - run: |
          cd composable
          go mod tidy
      - run: |
          cd git
          go mod tidy
      - run: |
          cd testutil
          go mod tidy
      - run: |
          cd util
          go mod tidy
      - run: git diff --exit-code
