name: Maestro CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.5
      - name: git config
        run: |
          git config --global init.defaultBranch main
          git config --global user.name "Adam McKee"
          git config --global user.email "adam.be.g84d@gmail.com"
      - name: build
        run: go build
      - name: test
        run: go list -f '{{.Dir}}' -m | xargs go test
      - name: tidy maestro
        run: go mod tidy
      - name: tidy composable
        run: |
          cd composable
          go mod tidy
      - name: tidy git
        run: |
          cd git
          go mod tidy
      - name: tidy testutil
        run: |
          cd testutil
          go mod tidy
      - name: tidy util
        run: |
          cd util
          go mod tidy
      - name: diff
        run: git diff --exit-code
